# Generated by Django 3.1.1 on 2020-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('codeforces', 'Codeforces'), ('uri', 'URI'), ('uva', 'UVA'), ('hackerrank', 'HackerRank'), ('lightoj', 'Light Oj')], default='codeforces', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=255)),
                ('explaination', models.CharField(max_length=10000)),
                ('code', models.CharField(max_length=10000)),
                ('img', models.ImageField(upload_to='images')),
                ('has_img', models.BooleanField(default=False)),
            ],
        ),
    ]
