# Generated by Django 3.1.1 on 2020-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.CharField(choices=[('codeforces', 'CODEFORCES'), ('uri', 'URI'), ('uva', 'UVA'), ('hackerrank', 'HACKERRANK'), ('lightoj', 'LIGHT Oj')], default='codeforces', max_length=10),
        ),
        migrations.AlterField(
            model_name='solution',
            name='explaination',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
