# Generated by Django 3.1.1 on 2020-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.CharField(choices=[('CODEFORCES', 'CODEFORCES'), ('URI', 'URI'), ('UVA', 'UVA'), ('HACKERRANK', 'HACKERRANK'), ('LIGHT Oj', 'LIGHT Oj')], default='codeforces', max_length=10),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='explaination',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
